export const UPDATE_TERM = 'UPDATE_TERM'
export const MOVE_CURSOR = 'MOVE_CURSOR'
export const SELECT_ELEMENT = 'SELECT_ELEMENT'
export const SHOW_RESULT = 'SHOW_RESULT'
export const HIDE_RESULT = 'HIDE_RESULT'
export const UPDATE_RESULT = 'UPDATE_RESULT'

export const RESET = 'RESET'
export const CHANGE_VISIBLE_RESULTS = 'CHANGE_VISIBLE_RESULTS'

export const ICON_LOADED = 'ICON_LOADED'

export const SET_STATUS_BAR_TEXT = 'SET_STATUS_BAR_TEXT'
